# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://postsal.github.io/
date_format: "ordinal"
title: MyBlog
subtitle: "Coding for happiness"
description: "胡建的个人博客"
keywords: 胡建
favicon: /favicon.ico
timezone: Asia/TangShan
encoding: "utf-8"
source_code: https://github.com/postsal/postsal.github.io
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 胡建
organization: 华北理工大学
organization_url: www.ncst.edu.cn
location: 唐山•中国
email: ihujian@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#  -
#    href: /MySkillTree/
#    label: 我的技能树

  -
    href: /about/
    label: 关于我

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Socials     #
# ---------------- #
github_username: postsal

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, changyan
comments_provider: disqus
# !!!重要!!! 请修改下面用户名为你自己申请的
disqus_username: postsal-github-io

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-82434482-1

# ---------------- #
#      Datas       #
# ---------------- #
skill_language_keywords: [Java,Go]
skill_web_app_keywords: [javaEE, Spring ,Spring MVC ,JPA , Hibernate , MyBatis, Shiro ,Redis ,Spring Data ,MySql,Entity Framework]
